const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let customers=JSON.parse(localStorage.getItem('jp_customers')||'[]');
let jobs=JSON.parse(localStorage.getItem('jp_jobs')||'[]');
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const cname=id=>customers.find(c=>c.id==id)?.name||'Onbekend';
function save(){localStorage.setItem('jp_customers',JSON.stringify(customers));localStorage.setItem('jp_jobs',JSON.stringify(jobs));render()}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active');$('#pageTitle').textContent=b.querySelector('span').textContent});
function openCustomer(){customerDialog.showModal()} window.openCustomer=openCustomer;
$('#headerNew').onclick=openCustomer;
customerForm.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));customers.unshift({...d,id:Date.now()});e.target.reset();customerDialog.close();save()};
function openJob(){if(!customers.length){alert('Maak eerst een klant aan.');return}jobCustomer.innerHTML=customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');jobDialog.showModal()} window.openJob=openJob;
jobForm.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));jobs.unshift({...d,id:Date.now(),customer:+d.customer,amount:+d.amount||0});e.target.reset();jobDialog.close();save()};
function delCustomer(id){if(confirm('Klant en gekoppelde opdrachten verwijderen?')){customers=customers.filter(c=>c.id!=id);jobs=jobs.filter(j=>j.customer!=id);save()}} window.delCustomer=delCustomer;
function delJob(id){if(confirm('Opdracht verwijderen?')){jobs=jobs.filter(j=>j.id!=id);save()}} window.delJob=delJob;
function whatsapp(phone){let p=String(phone||'').replace(/\D/g,'');if(p.startsWith('0'))p='31'+p.slice(1);return p}
function renderCustomers(){let q=($('#searchCustomer').value||'').toLowerCase();let rows=customers.filter(c=>Object.values(c).join(' ').toLowerCase().includes(q));customerRows.innerHTML=rows.map(c=>`<tr><td><b>${esc(c.name)}</b>${c.notes?`<div class="muted">${esc(c.notes)}</div>`:''}</td><td>${c.phone?`<a href="tel:${esc(c.phone)}">${esc(c.phone)}</a>`:''}<br><span class="muted">${esc(c.email)}</span></td><td>${esc(c.address)}</td><td>${c.phone?`<a target="_blank" href="https://wa.me/${whatsapp(c.phone)}">WhatsApp</a> · `:''}<a href="#" onclick="delCustomer(${c.id});return false">Verwijder</a></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Geen klanten gevonden</td></tr>'}
$('#searchCustomer').oninput=renderCustomers;
function renderJobs(){let f=jobFilter.value;let arr=jobs.filter(j=>!f||j.status==f);jobCards.innerHTML=arr.map(j=>`<article><span class="badge">${esc(j.status)}</span><strong>${esc(j.title)}</strong><p>${esc(cname(j.customer))}</p>${j.date?`<p>📅 ${new Date(j.date).toLocaleString('nl-NL',{dateStyle:'medium',timeStyle:'short'})}</p>`:''}${j.amount?`<b>€ ${j.amount.toLocaleString('nl-NL',{minimumFractionDigits:2})}</b>`:''}${j.notes?`<p>${esc(j.notes)}</p>`:''}<p><a href="#" onclick="delJob(${j.id});return false">Verwijderen</a></p></article>`).join('')||'<div class="empty">Geen opdrachten</div>'}
jobFilter.onchange=renderJobs;
function render(){customerCount.textContent=customers.length;openCount.textContent=jobs.filter(j=>!['Afgerond','Gefactureerd'].includes(j.status)).length;let now=new Date(),week=new Date(now);week.setDate(now.getDate()+7);weekCount.textContent=jobs.filter(j=>j.date&&new Date(j.date)>=now&&new Date(j.date)<=week).length;revenue.textContent='€ '+jobs.filter(j=>['Afgerond','Gefactureerd'].includes(j.status)).reduce((a,j)=>a+j.amount,0).toLocaleString('nl-NL',{minimumFractionDigits:2});recentJobs.innerHTML=jobs.slice(0,5).map(j=>`<div class="item"><b>${esc(j.title)}</b><span class="badge">${esc(j.status)}</span><br><small>${esc(cname(j.customer))}</small></div>`).join('')||'<div class="empty">Nog geen opdrachten</div>';let ds=now.toLocaleDateString('sv-SE');today.innerHTML=jobs.filter(j=>j.date?.slice(0,10)==ds).map(j=>`<div class="item"><b>${new Date(j.date).toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})} · ${esc(j.title)}</b><br><small>${esc(cname(j.customer))}</small></div>`).join('')||'<div class="empty">Geen afspraken vandaag</div>';renderCustomers();renderJobs();planningList.innerHTML=jobs.filter(j=>j.date).sort((a,b)=>new Date(a.date)-new Date(b.date)).map(j=>`<div class="item"><b>${new Date(j.date).toLocaleString('nl-NL',{dateStyle:'medium',timeStyle:'short'})}</b> — ${esc(j.title)}<span class="badge">${esc(cname(j.customer))}</span></div>`).join('')||'<div class="empty">Planning is leeg</div>'}
render();